@startuml
'https://plantuml.com/class-diagram

class WorldMapFactory {
}
interface WorldMap {
    getTiles() : [][]Tile
}
class AntWorldMap {
}
class Tile {
}

WorldMapFactory -[dashed]-> WorldMap
AntWorldMap *-> Tile : [][]tiles
AntWorldMap --|> WorldMap

@enduml