@startuml



class World {


}


interface Object {

}

class Tile {

}

class Pheromone {
    - quantity: int
    - geneticMarker: char
    getQuantity()
}

class WorldMap


Object <|-- Rock
Object <|-- Food
Object <|-- Colony

World -> WorldMap : map
WorldMap *-> Tile : [][]tiles
Tile *-> Object : object
Tile *--> Ant : []ants
Tile *--> Pheromone : []pheromones





@enduml